// <auto-generated />
using System;
using FamLedger.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamLedger.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820081954_AddPeriodRecurringItemIsSkipped")]
    partial class AddPeriodRecurringItemIsSkipped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamLedger.Domain.Entities.BudgetContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PeriodStartDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("budget_contexts", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CarryoverBase")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContextId", "StartDate");

                    b.ToTable("budget_periods", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.ContextMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ContextId", "UserId")
                        .IsUnique();

                    b.ToTable("context_members", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("CounterpartyUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.HasIndex("CounterpartyUserId");

                    b.ToTable("debts", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.DebtEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("debt_entries", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RateToRsd")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Currency")
                        .IsUnique();

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.GoalContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("goal_contributions", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("ReceivedRate")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.ToTable("incomes", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.HasIndex("UserId");

                    b.ToTable("join_requests", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.NotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notification_subscriptions", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.OneOffExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.HasIndex("PeriodId");

                    b.ToTable("one_off_expenses", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.PeriodRecurringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedBaseAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecurringExpenseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecurringExpenseId");

                    b.HasIndex("PeriodId", "RecurringExpenseId")
                        .IsUnique();

                    b.ToTable("period_recurring_items", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.RateOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RateToRsd")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.HasIndex("PeriodId");

                    b.ToTable("rate_overrides", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChargeDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefinitionAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("DefinitionCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("RecalcByRate")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SourceIncomeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContextId");

                    b.ToTable("recurring_expenses", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.SavingsEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ContextId", "PeriodId")
                        .IsUnique();

                    b.ToTable("savings_entries", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContextId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PeriodId", "Date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveContextId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("webhook_endpoints", (string)null);
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.BudgetPeriod", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Periods")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Category", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Categories")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.ContextMember", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Members")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Debt", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Debts")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.User", "CounterpartyUser")
                        .WithMany()
                        .HasForeignKey("CounterpartyUserId");

                    b.Navigation("Context");

                    b.Navigation("CounterpartyUser");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.DebtEntry", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.Debt", "Debt")
                        .WithMany("Entries")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Goal", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Goals")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.GoalContribution", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.Goal", "Goal")
                        .WithMany("Contributions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Income", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Incomes")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("JoinRequests")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.User", "User")
                        .WithMany("JoinRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.NotificationSubscription", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.OneOffExpense", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("OneOffExpenses")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.BudgetPeriod", "Period")
                        .WithMany("OneOffExpenses")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.PeriodRecurringItem", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetPeriod", "Period")
                        .WithMany("RecurringItems")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.RecurringExpense", "RecurringExpense")
                        .WithMany("PeriodItems")
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("RecurringExpense");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.RateOverride", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany()
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.BudgetPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");

                    b.Navigation("Context");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.RecurringExpense", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("RecurringExpenses")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Context");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.SavingsEntry", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("SavingsEntries")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.BudgetPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "Context")
                        .WithMany("Transactions")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamLedger.Domain.Entities.BudgetPeriod", "Period")
                        .WithMany("Transactions")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Context");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.User", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.BudgetContext", "ActiveContext")
                        .WithMany()
                        .HasForeignKey("ActiveContextId");

                    b.Navigation("ActiveContext");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("FamLedger.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.BudgetContext", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Debts");

                    b.Navigation("Goals");

                    b.Navigation("Incomes");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("OneOffExpenses");

                    b.Navigation("Periods");

                    b.Navigation("RecurringExpenses");

                    b.Navigation("SavingsEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Navigation("OneOffExpenses");

                    b.Navigation("RecurringItems");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Debt", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.Goal", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.RecurringExpense", b =>
                {
                    b.Navigation("PeriodItems");
                });

            modelBuilder.Entity("FamLedger.Domain.Entities.User", b =>
                {
                    b.Navigation("JoinRequests");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
